### ISSUE TITLE
Can links be made to work in zoom view?

### ISSUE THREAD

**Issue by perdittmann** [blasten/turn.js#126]
Hi,

I am working on a flipbook for a client who wants the links on pages to also work when the page is zoomed.

Is it possible to get there (can the regions file also be read out (and resized) in the zoom view?), or do I have to hope for another release? :-)

Many thanks for any advice on that!

**Comment by blasten** [comment]
@perdittmann you can change the CSS, so all regions will show up when the page is zoomed.

``` css

.magazine-viewport .zoomer .region{
    display:none;
}

.magazine-viewport .zoom-in .region{
    display:none;
}
```
