### ISSUE TITLE
Hard cover turning animation

### ISSUE THREAD

**Issue by beckiechoi** [blasten/turn.js#196]
I was wondering if I could reproduce the Steve Job's sample where the hard cover page folding is animated in a way that the sides become wider, making it seem closer and more realistic. I tried to find any property that might set this, but couldn't find it..(I use turn.js4)

Thanks in advance :)

**Comment by dbwinger** [comment]
Did you find an answer to this.  I was actually just trying to figure out the same thing today.  I think the only requirement is setting the perspective (and browser equivalents) CSS property on the .page-wrapper class.  
ie:

``` CSS
  .page-wrapper {
      -webkit-perspective:1500px;
      -moz-perspective: 1500px;
      -ms-perspective: 1500px;
      perspective: 1500px;
  }
```
