### ISSUE TITLE
On iOS3  corners show the entire next/previous page

### ISSUE THREAD

**Issue by trouille2** [blasten/turn.js#204]
Hello, 
I'm testing the flipbook on iphone 3 and 4, on the old one, the flipbook is really slow and when we try to turn the page, the next/previous page appears rotated on the corner in full size (I mean not hidden).

**Comment by blasten** [comment]
@trouille2 That's is weird. Are you using 3rd or 4th release?

**Comment by trouille2** [comment]
The 4th release.

**Comment by blasten** [comment]
I figured out that box-shadows ( a CSS option used in  4th release)  works really slow, so the next update would make it optional. Please remove it by adding the following CSS:

``` css
#flipbook .page{
    -webkit-box-shadow:none !important;
    -moz-box-shadow:none !important;
    -ms-box-shadow:none !important;
    -o-box-shadow: none !important;
    box-shadow:none !important;
}
```

Make sure to replace the `#flipbook` with the selector of your book/magazine.
