### ISSUE TITLE
Cover Thickness

### ISSUE THREAD

**Issue by grossmaninc** [blasten/turn.js#224]
Can anyone tell me how to make the cover thicker?  I see it on the turnjs site for the Steve Jobs example, however cant seem to figure this out - to make the hard cover appear thicker than 1pixel...

Thanks again for this great product!

Adam
GrossmanInteractive.com

**Comment by blasten** [comment]
@grossmaninc  
1. Add perspective to the hard page: http://turnjs.com/docs/Class:_.hard
2. To achieve the depth, you can add the "depth" attribute to the div element of the page.   For example:

``` HTML
<div class="hard" depth="5"> Page's content </div>
```

In that case 5 is the number of pixels.  Please add the same attribute to all the covers.

**Comment by beckiechoi** [comment]
Can you specify where to put in the thickness element in html, and what CSS styles are needed?
In the Steve Jobs example on your site, you use .depth as the stacked pages, so it's a bit confusing.

**Comment by blasten** [comment]
HTML:

``` html
<div id="flipbook">
<div class="hard p1" depth="5"> <div class="side"></div> </div>
<div class="hard p2" depth="5"> </div>
<div class="p3"> Internal page 1 </div>
<div class="p4"> Internal page 2 </div>
<div class="p5"> Internal page 3 </div>
<div class="p6"> Internal page 4 </div>
<div class="p7"> Internal page 5 </div>
<div class="hard p8" depth="5"> <div class="side"></div> </div>
<div class="hard p9" depth="5"> </div>
</div>
```

CSS:

``` css

#flipbook{
  width:960px;
   height:600px;
}

#flipbook .p1 .side{
  width:5px;
  height:600px;
  position:absolute;
  top:0;
  left:475px;
  background-color:gray;
  -webkit-transform:rotateY(-90deg);
  -moz-transform:rotateY(-90deg);
  -o-transform:rotateY(-90deg);
  -ms-transform:rotateY(-90deg);
  transform:rotateY(-90deg);
  -webkit-transform-origin:top right;
  -moz-transform-origin:top right;
  -o-transform-origin:top right;
  -ms-transform-origin:top right;
  transform-origin:top right;
  z-index:100000;
}
```
