### ISSUE TITLE
Rounded page corners

### ISSUE THREAD

**Issue by dmpneuro** [blasten/turn.js#228]
Assuming a turnjs flipbook with hard covers and smaller (own-size) pages (like steve-jobs book), how would I go about rounding the cover page corners? When I use css radius, the corners round but there is a small white area in the remaining corners that I can't seem to get rid of. Any thoughts? Thanks.

**Comment by blasten** [comment]
Does all the pages have the same border-radius? I'd suggest to use the **.odd** and **.even** classes because the position of corners would depend upon whether the page is at the right or at the left.

Something like:

``` css
#flipbook .odd{
 -webkit-border-top-right-radius: 20px;
 -webkit-border-bottom-right-radius: 20px;
}

#flipbook .odd{
 -webkit-border-top-left-radius: 20px;
 -webkit-border-bottom-left-radius: 20px;
}

```
