### ISSUE TITLE
Shadows to make pages look like a book?

### ISSUE THREAD

**Issue by relipse** [blasten/turn.js#258]
How can I get the shadow crinkly gradient thing to appear so it appears like a real book (like magazine demo etc)?
I am using turnjs4

For example go to http://blackcell.co.za/turnjs4/turnjs4/samples/steve-jobs/#page/4
Look in the center of the book, there are 2 long shadows. Where does this come from and why is it disabled in my own example?

**Comment by blasten** [comment]
Those shadows are coming from the file samples/steve-jobs/css/steve-jobs.css

``` css
.sj-book .even{
    background:-webkit-gradient(linear, left top, right top, color-stop(0.95, #fff), color-stop(1, #dadada));
    background-image:-webkit-linear-gradient(left, #fff 95%, #dadada 100%);
    background-image:-moz-linear-gradient(left, #fff 95%, #dadada 100%);
    background-image:-ms-linear-gradient(left, #fff 95%, #dadada 100%);
    background-image:-o-linear-gradient(left, #fff 95%, #dadada 100%);
    background-image:linear-gradient(left, #fff 95%, #dadada 100%);
}

.sj-book .odd{
    background:-webkit-gradient(linear, right top, left top, color-stop(0.95, #fff), color-stop(1, #cacaca));
    background-image:-webkit-linear-gradient(right, #fff 95%, #cacaca 100%);
    background-image:-moz-linear-gradient(right, #fff 95%, #cacaca 100%);
    background-image:-ms-linear-gradient(right, #fff 95%, #cacaca 100%);
    background-image:-o-linear-gradient(right, #fff 95%, #cacaca 100%);
    background-image:linear-gradient(right, #fff 95%, #cacaca 100%);
}
```
