### ISSUE TITLE
Adding a preloader

### ISSUE THREAD

**Issue by danitoto** [blasten/turn.js#270]
Hi!

I´m setting up a mag which contains 68 pages that range from 250kbs to 300kbs each one. I would like to add a method to show a preloader in case the page is not ready yet. How should I work this?

Thanks for any tip!

**Comment by blasten** [comment]
@danitoto Do you add your pages dynamically, I mean using `addPage`? If so, please check this out:

``` javascript
function addPage(page, book) {
    var element = $('<div />');

    if (book.turn('addPage', element, page)) {
        // Add the initial HTML
        element.html('<div class="loader"></div>');
        loadPage(page, element);
    }
}

function loadPage(page, pageElement) {

    // Create an image element

    var img = $('<img />');
    img.load(function() {
      $(this).appendTo(pageElement);
          // remove the loader
      pageElement.find('.loader').remove();
    });

    img.attr('src', 'pages/' +  page + '-large.jpg');
}

```

CSS:

``` css
#flipbook .loader{
    background-image:url(../pics/loader.gif);
    width:22px;
    height:22px;
    position:absolute;
    top:280px;
    left:219px;
}
```
