### ISSUE TITLE
Page-wrapper Overflow

### ISSUE THREAD

**Issue by alQemist** [blasten/turn.js#328]
magazine-viewport somewhere has style set to overflow:hidden - where can I change the JS to set overflow to visible ?
turn.js version 4. Magazine example.

**Comment by blasten** [comment]
That is automatically set by turn.js 4th release. The only way to replace is using

``` css
.magazine-viewport{
   overflow:visible !important;
}
```
