### ISSUE TITLE
Not display correctly for me !

### ISSUE THREAD

**Issue by hamidhadi** [blasten/turn.js#511]
I have big problem. turn.js is not working correctly for me. I tested different codes but it's not working. 
you can see the one of the problem in below 
![screen shot 1394-01-23 at 11 46 14 am](https://cloud.githubusercontent.com/assets/6258297/7104722/0514d1f2-e10a-11e4-944c-25359290593f.png)

here is my js code: 

``` javascript
    $('#magazine').turn({
              display: 'double',
              acceleration: true,
              gradients: !$.isTouch,
              elevation:50,
              when: {
                turned: function(e, page) {
                  /*console.log('Current view: ', $(this).turn('view'));*/
                }
              }
            });
```

and here is css codes: 

``` css
.com{
    width: 100%;
    height: 100%;
    position: fixed;
    top: 0;
    left: 0;
    z-index: 9999999999999;
    &>div{
        margin: 0 auto;
    }
}
#magazine {
    width:700px;
    height:600px
}
#magazine .turn-page-wrapper{
    -webkit-perspective:2000px;
    -moz-perspective: 2000px;
    -ms-perspective: 2000px;
    perspective: 2000px;
}
```

and the html codes:

``` html
                <div class="com">
                  <div id="magazine">
            <div class="own-size"><img src="https://raw.github.com/blasten/turn.js/master/demos/magazine/pages/01.jpg" alt="" /></div>
            <div class="own-size p2"><img src="https://raw.github.com/blasten/turn.js/master/demos/magazine/pages/02.jpg" alt="" /></div>
            <div class="own-size p3"><img src="https://raw.github.com/blasten/turn.js/master/demos/magazine/pages/03.jpg" alt="" /></div>
            <div class="own-size"><img src="https://raw.github.com/blasten/turn.js/master/demos/magazine/pages/04.jpg" alt="" /></div>
            <div class="own-size"><img src="https://raw.github.com/blasten/turn.js/master/demos/magazine/pages/05.jpg" alt="" /></div>
            <div class="own-size"><img src="https://raw.github.com/blasten/turn.js/master/demos/magazine/pages/06.jpg" alt="" /></div>
                  </div>
                </div>
```
